sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tQvD4Po2sqMbTSzRf82
    access-key-secret: OJEewvRFJGJgDxdBctnVE2pD7XRzXC
    bucket-name: amigo2012

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wxd4054508c82e1a7c
    secret: 242416cc1662426246ef8216309d6859